config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :posts
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show 
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode 

  validates :name, presence: true, length: { minimum: 3, too_short: "must be at least %{count} characters long" }
  validates :address, presence: true
  validates :description, presence: true
#  validate :image_size_validation

  private

#  def image_size_validation
#      errors[:picture] <<"should be less than 1MB" if picture.image.size > 1.megabytes
#  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.paginate(:page => params[:page], :per_page => 2)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address, :picture, :caption, :place_id)
  end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit your place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Looking for some great music?</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider2.jpg', class: 'img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Combined with good food?</h3>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'img-fluid' %>
      <div class="carousel-caption d-none d-md-block">
        <h3>Looking for your new favorite bar?</h3>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<% @places.each do |place| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

    <% if place.comments.present? %>
      <div class="col-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>

    <% if place.photos.present? %>  
      <div class="col-6">
        <% if place.photos.last.present? %>
          <b><%= place.photos.last %></b> 
        <% end %>
        <%= place.photos.last.caption %>
      </div>
    <% end %>
  </div>
<% end %>
<br /><br /><br />
<%= will_paginate @places %>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-12">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>

 
    <script>

      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 14,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvrZKNetxiMQEydU7J5X74WXRmc-P9avw&callback=initMap">
    </script>

    <div id="map"></div>

  <div class="float-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
  </div>
  
</div> 

<div class="clear"></div>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-medium" data-toggle="modal" data-target="#myModal1">
  Add a photo
</button>

<br /><br /><br /><br />

<!-- Modal -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel1">Add a Photo</h4>
      </div>
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
          <div class="modal-body">
            <%= f.input :picture %>
            <%= f.input :caption %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
          </div>
        <% end %>  
    </div>
  </div>
</div>

<div class="row">
  <% @place.photos.each do |photo| %>
    <div class="col-12 col-sm-6">
        <%= photo.caption %>
        <%= image_tag photo.picture.url %>
    </div>
  <% end %>
</div>

<div class="clear"></div>

<div class="col-10 offset-1">
  <h1 class="float-left">Comments</h1>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-medium" data-toggle="modal" data-target="#myModal">
  Add a comment
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
      </div>
      <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
          <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

</div>

<div class="clear"></div>

<div class="row">
  <% @place.comments.each do |comment| %>
    <div class="col-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>


<%#Photo.create :place_id => 1000, :caption => "Chicago kingston mines", :user_id => 999, :created_at => "1/2/19", :updated_at=>"1:34", :picture =>"111", :id=> 12345%>